from core.utils import strip_dict_strs


def get_state_lut():
    states = [
        {"st_key": -2, "fips_st_cd": "TC", "st_nm": "Fake State for Test"},
        {"st_key": -1, "fips_st_cd": "AY", "st_nm": "Antarctica"},
        {"st_key": 1, "fips_st_cd": "AK", "st_nm": "ALASKA"},
        {"st_key": 2, "fips_st_cd": "AL", "st_nm": "ALABAMA"},
        {"st_key": 3, "fips_st_cd": "AZ", "st_nm": "ARIZONA"},
        {"st_key": 4, "fips_st_cd": "AR", "st_nm": "ARKANSAS"},
        {"st_key": 5, "fips_st_cd": "CA", "st_nm": "CALIFORNIA"},
        {"st_key": 6, "fips_st_cd": "CO", "st_nm": "COLORADO"},
        {"st_key": 7, "fips_st_cd": "CT", "st_nm": "CONNECTICUT"},
        {"st_key": 8, "fips_st_cd": "DC", "st_nm": "DISTRICT OF COLUMBIA"},
        {"st_key": 9, "fips_st_cd": "DE", "st_nm": "DELAWARE"},
        {"st_key": 10, "fips_st_cd": "FL", "st_nm": "FLORIDA"},
        {"st_key": 11, "fips_st_cd": "GA", "st_nm": "GEORGIA"},
        {"st_key": 12, "fips_st_cd": "HI", "st_nm": "HAWAII"},
        {"st_key": 13, "fips_st_cd": "IA", "st_nm": "IOWA"},
        {"st_key": 14, "fips_st_cd": "ID", "st_nm": "IDAHO"},
        {"st_key": 15, "fips_st_cd": "IL", "st_nm": "ILLINOIS"},
        {"st_key": 16, "fips_st_cd": "IN", "st_nm": "INDIANA"},
        {"st_key": 17, "fips_st_cd": "KS", "st_nm": "KANSAS"},
        {"st_key": 18, "fips_st_cd": "KY", "st_nm": "KENTUCKY"},
        {"st_key": 19, "fips_st_cd": "LA", "st_nm": "LOUISIANA"},
        {"st_key": 20, "fips_st_cd": "MA", "st_nm": "MASSACHUSETTES"},
        {"st_key": 21, "fips_st_cd": "MD", "st_nm": "MARYLAND"},
        {"st_key": 22, "fips_st_cd": "ME", "st_nm": "MAINE"},
        {"st_key": 23, "fips_st_cd": "MI", "st_nm": "MICHIGAN"},
        {"st_key": 24, "fips_st_cd": "MN", "st_nm": "MINNESOTA"},
        {"st_key": 25, "fips_st_cd": "MO", "st_nm": "MISSOURI"},
        {"st_key": 26, "fips_st_cd": "MS", "st_nm": "MISSISSIPPI"},
        {"st_key": 27, "fips_st_cd": "MT", "st_nm": "MONTANA"},
        {"st_key": 28, "fips_st_cd": "NC", "st_nm": "NORTH CAROLINA"},
        {"st_key": 29, "fips_st_cd": "ND", "st_nm": "NORTH DAKOTA"},
        {"st_key": 30, "fips_st_cd": "NE", "st_nm": "NEBRASKA"},
        {"st_key": 31, "fips_st_cd": "NH", "st_nm": "NEW HAMPSHIRE"},
        {"st_key": 32, "fips_st_cd": "NJ", "st_nm": "NEW JERSEY"},
        {"st_key": 33, "fips_st_cd": "NM", "st_nm": "NEW MEXICO"},
        {"st_key": 34, "fips_st_cd": "NV", "st_nm": "NEVADA"},
        {"st_key": 35, "fips_st_cd": "NY", "st_nm": "NEW YORK"},
        {"st_key": 36, "fips_st_cd": "OH", "st_nm": "OHIO"},
        {"st_key": 37, "fips_st_cd": "OK", "st_nm": "OKLAHOMA"},
        {"st_key": 38, "fips_st_cd": "OR", "st_nm": "OREGON"},
        {"st_key": 39, "fips_st_cd": "PA", "st_nm": "PENNSYLVANIA"},
        {"st_key": 40, "fips_st_cd": "RI", "st_nm": "RHODE ISLAND"},
        {"st_key": 41, "fips_st_cd": "SC", "st_nm": "SOUTH CAROLINA"},
        {"st_key": 42, "fips_st_cd": "SD", "st_nm": "SOUTH DAKOTA"},
        {"st_key": 43, "fips_st_cd": "TN", "st_nm": "TENNESSEE"},
        {"st_key": 44, "fips_st_cd": "TX", "st_nm": "TEXAS"},
        {"st_key": 45, "fips_st_cd": "UT", "st_nm": "UTAH"},
        {"st_key": 46, "fips_st_cd": "VA", "st_nm": "VIRGINIA"},
        {"st_key": 47, "fips_st_cd": "VT", "st_nm": "VERMONT"},
        {"st_key": 48, "fips_st_cd": "WA", "st_nm": "WASHINGTON"},
        {"st_key": 49, "fips_st_cd": "WI", "st_nm": "WISCONSIN"},
        {"st_key": 50, "fips_st_cd": "WV", "st_nm": "WEST VIRGINIA"},
        {"st_key": 51, "fips_st_cd": "WY", "st_nm": "WYOMING"},
        {"st_key": 52, "fips_st_cd": "AS", "st_nm": "AMERICAN SAMOA"},
        {"st_key": 53, "fips_st_cd": "FM", "st_nm": "FED STATES OF MICRONESIA"},
        {"st_key": 54, "fips_st_cd": "GU", "st_nm": "GUAM"},
        {"st_key": 55, "fips_st_cd": "MH", "st_nm": "MARSHALL ISLANDS"},
        {"st_key": 56, "fips_st_cd": "MP", "st_nm": "NORTHERN MARIANA ISLANDS"},
        {"st_key": 57, "fips_st_cd": "PW", "st_nm": "PALAU"},
        {"st_key": 58, "fips_st_cd": "PR", "st_nm": "PUERTO RICO"},
        {"st_key": 59, "fips_st_cd": "UM", "st_nm": "US MINOR OUTLYING ISLANDS"},
        {"st_key": 60, "fips_st_cd": "VI", "st_nm": "VIRGIN ISLANDS OF THE US"},
        {"st_key": 61, "fips_st_cd": "AB", "st_nm": "ALBERTA"},
        {"st_key": 62, "fips_st_cd": "BC", "st_nm": "BRITISH COLUMBIA"},
        {"st_key": 63, "fips_st_cd": "YK", "st_nm": "YUKON TERRITORY"},
        {"st_key": 64, "fips_st_cd": "MB", "st_nm": "MANITOBA"},
        {"st_key": 65, "fips_st_cd": "NB", "st_nm": "NEW BRUNSWICK"},
        {"st_key": 66, "fips_st_cd": "NL", "st_nm": "NEWFOUNDLAND AND LABRADOR"},
        {"st_key": 67, "fips_st_cd": "NS", "st_nm": "NOVA SCOTIA"},
        {"st_key": 68, "fips_st_cd": "NT", "st_nm": "NORTHWEST TERRITORIES"},
        {"st_key": 69, "fips_st_cd": "NU", "st_nm": "NUNAVUT"},
        {"st_key": 70, "fips_st_cd": "ON", "st_nm": "ONTARIO"},
        {"st_key": 71, "fips_st_cd": "PE", "st_nm": "PRINCE EDWARD ISLAND"},
        {"st_key": 72, "fips_st_cd": "QC", "st_nm": "QUEBEC"},
        {"st_key": 73, "fips_st_cd": "SK", "st_nm": "SASKATCHEWAN"},
        {"st_key": 999, "fips_st_cd": "NA", "st_nm": "NOT APPLICABLE"},
    ]
    states[:] = [strip_dict_strs(_) for _ in states]
    return {_["st_key"]: _ for _ in states}


def get_network_lut():
    networks = [
        {"ntwk_key": 1, "ntwk_cd": "COOP    ", "ntwk_nm": "COOPERATOR PRECIP GAUGES"},
        {"ntwk_key": 5, "ntwk_cd": "SNTL    ", "ntwk_nm": "SNOTEL"},
        {"ntwk_key": 6, "ntwk_cd": "SNOW    ", "ntwk_nm": "SNOW COURSE\/AERIAL MARKER"},
        {"ntwk_key": 7, "ntwk_cd": "USGS    ", "ntwk_nm": "STREAMFLOW"},
        {"ntwk_key": 8, "ntwk_cd": "BOR     ", "ntwk_nm": "RESERVOIR"},
        {"ntwk_key": 9, "ntwk_cd": "SCAN    ", "ntwk_nm": "SCAN"},
        {"ntwk_key": 10, "ntwk_cd": "MPRC    ", "ntwk_nm": "MANUAL PRECIPITATION"},
        {"ntwk_key": 11, "ntwk_cd": "MSNT    ", "ntwk_nm": "COOPERATOR SNOW SENSORS"},
        {"ntwk_key": 13, "ntwk_cd": "CLMIND  ", "ntwk_nm": "CLIMATE INDEX"},
        {"ntwk_key": 14, "ntwk_cd": "CSCAN   ", "ntwk_nm": "TRIBAL SCAN"},
        {"ntwk_key": 15, "ntwk_cd": "SNTLT   ", "ntwk_nm": "SNOLITE"},
        {"ntwk_key": 16, "ntwk_cd": "AEMARK  ", "ntwk_nm": "AERIAL MARKER"},
        {"ntwk_key": 17, "ntwk_cd": "NRCSXP  ", "ntwk_nm": "NRCS Experimental"},
        {"ntwk_key": 18, "ntwk_cd": "OTHER   ", "ntwk_nm": "Other NRCS Hydromet"},
        {"ntwk_key": 19, "ntwk_cd": "UCOOP   ", "ntwk_nm": "UNUSED COOP"},
        {"ntwk_key": 20, "ntwk_cd": "USNTL   ", "ntwk_nm": "UNUSED SNTL"},
        {"ntwk_key": 21, "ntwk_cd": "USCAN   ", "ntwk_nm": "UNUSED SCAN"},
        {"ntwk_key": 999, "ntwk_cd": "NA      ", "ntwk_nm": "NOT APPLICABLE"},
    ]
    networks[:] = [strip_dict_strs(_) for _ in networks]
    return {_["ntwk_key"]: _ for _ in networks}
